apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: givegetgo-user-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/GiveGetGo/givegetgo-backend.git'
    path: 'charts/user'
    targetRevision: main
  destination:
    server: "https://kubernetes.default.svc"
    namespace: givegetgo-production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
