// Code generated by MockGen. DO NOT EDIT.
// Source: utils/user_utils.go

// Package utils is a generated GoMock package.
package utils

import (
	context "context"
	reflect "reflect"
	schema "user/schema"

	types "github.com/GiveGetGo/shared/types"
	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockIUserUtils is a mock of IUserUtils interface.
type MockIUserUtils struct {
	ctrl     *gomock.Controller
	recorder *MockIUserUtilsMockRecorder
}

// MockIUserUtilsMockRecorder is the mock recorder for MockIUserUtils.
type MockIUserUtilsMockRecorder struct {
	mock *MockIUserUtils
}

// NewMockIUserUtils creates a new mock instance.
func NewMockIUserUtils(ctrl *gomock.Controller) *MockIUserUtils {
	mock := &MockIUserUtils{ctrl: ctrl}
	mock.recorder = &MockIUserUtilsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUserUtils) EXPECT() *MockIUserUtilsMockRecorder {
	return m.recorder
}

// AuthenticateUser mocks base method.
func (m *MockIUserUtils) AuthenticateUser(user schema.User, password string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthenticateUser", user, password)
	ret0, _ := ret[0].(bool)
	return ret0
}

// AuthenticateUser indicates an expected call of AuthenticateUser.
func (mr *MockIUserUtilsMockRecorder) AuthenticateUser(user, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthenticateUser", reflect.TypeOf((*MockIUserUtils)(nil).AuthenticateUser), user, password)
}

// CheckEmailVerificationSession mocks base method.
func (m *MockIUserUtils) CheckEmailVerificationSession(ctx context.Context, userID uint, event string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckEmailVerificationSession", ctx, userID, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckEmailVerificationSession indicates an expected call of CheckEmailVerificationSession.
func (mr *MockIUserUtilsMockRecorder) CheckEmailVerificationSession(ctx, userID, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckEmailVerificationSession", reflect.TypeOf((*MockIUserUtils)(nil).CheckEmailVerificationSession), ctx, userID, event)
}

// CreateUser mocks base method.
func (m *MockIUserUtils) CreateUser(username, email, hashedPassword, class, major string) (schema.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", username, email, hashedPassword, class, major)
	ret0, _ := ret[0].(schema.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockIUserUtilsMockRecorder) CreateUser(username, email, hashedPassword, class, major interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockIUserUtils)(nil).CreateUser), username, email, hashedPassword, class, major)
}

// DeleteUser mocks base method.
func (m *MockIUserUtils) DeleteUser(userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockIUserUtilsMockRecorder) DeleteUser(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockIUserUtils)(nil).DeleteUser), userID)
}

// GenerateAndSendQRCode mocks base method.
func (m *MockIUserUtils) GenerateAndSendQRCode(c *gin.Context, email string, secret []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GenerateAndSendQRCode", c, email, secret)
}

// GenerateAndSendQRCode indicates an expected call of GenerateAndSendQRCode.
func (mr *MockIUserUtilsMockRecorder) GenerateAndSendQRCode(c, email, secret interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAndSendQRCode", reflect.TypeOf((*MockIUserUtils)(nil).GenerateAndSendQRCode), c, email, secret)
}

// GetUserByEmail mocks base method.
func (m *MockIUserUtils) GetUserByEmail(email string) (schema.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", email)
	ret0, _ := ret[0].(schema.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockIUserUtilsMockRecorder) GetUserByEmail(email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockIUserUtils)(nil).GetUserByEmail), email)
}

// GetUserByID mocks base method.
func (m *MockIUserUtils) GetUserByID(userID uint) (schema.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", userID)
	ret0, _ := ret[0].(schema.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockIUserUtilsMockRecorder) GetUserByID(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockIUserUtils)(nil).GetUserByID), userID)
}

// HashPassword mocks base method.
func (m *MockIUserUtils) HashPassword(password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HashPassword", password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HashPassword indicates an expected call of HashPassword.
func (mr *MockIUserUtilsMockRecorder) HashPassword(password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HashPassword", reflect.TypeOf((*MockIUserUtils)(nil).HashPassword), password)
}

// MarkEmailVerified mocks base method.
func (m *MockIUserUtils) MarkEmailVerified(email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkEmailVerified", email)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkEmailVerified indicates an expected call of MarkEmailVerified.
func (mr *MockIUserUtilsMockRecorder) MarkEmailVerified(email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkEmailVerified", reflect.TypeOf((*MockIUserUtils)(nil).MarkEmailVerified), email)
}

// MarkMFAVerified mocks base method.
func (m *MockIUserUtils) MarkMFAVerified(userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkMFAVerified", userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkMFAVerified indicates an expected call of MarkMFAVerified.
func (mr *MockIUserUtilsMockRecorder) MarkMFAVerified(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkMFAVerified", reflect.TypeOf((*MockIUserUtils)(nil).MarkMFAVerified), userID)
}

// RequestForgetpassVerificationEmail mocks base method.
func (m *MockIUserUtils) RequestForgetpassVerificationEmail(userID uint, username, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestForgetpassVerificationEmail", userID, username, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequestForgetpassVerificationEmail indicates an expected call of RequestForgetpassVerificationEmail.
func (mr *MockIUserUtilsMockRecorder) RequestForgetpassVerificationEmail(userID, username, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestForgetpassVerificationEmail", reflect.TypeOf((*MockIUserUtils)(nil).RequestForgetpassVerificationEmail), userID, username, email)
}

// RequestRegisterVerificationEmail mocks base method.
func (m *MockIUserUtils) RequestRegisterVerificationEmail(userID uint, username, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestRegisterVerificationEmail", userID, username, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequestRegisterVerificationEmail indicates an expected call of RequestRegisterVerificationEmail.
func (mr *MockIUserUtilsMockRecorder) RequestRegisterVerificationEmail(userID, username, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestRegisterVerificationEmail", reflect.TypeOf((*MockIUserUtils)(nil).RequestRegisterVerificationEmail), userID, username, email)
}

// StoreEncryptedTOTPSecret mocks base method.
func (m *MockIUserUtils) StoreEncryptedTOTPSecret(userID uint, encryptedSecret string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreEncryptedTOTPSecret", userID, encryptedSecret)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreEncryptedTOTPSecret indicates an expected call of StoreEncryptedTOTPSecret.
func (mr *MockIUserUtilsMockRecorder) StoreEncryptedTOTPSecret(userID, encryptedSecret interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreEncryptedTOTPSecret", reflect.TypeOf((*MockIUserUtils)(nil).StoreEncryptedTOTPSecret), userID, encryptedSecret)
}

// UpdatePassword mocks base method.
func (m *MockIUserUtils) UpdatePassword(userID uint, hashedPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", userID, hashedPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockIUserUtilsMockRecorder) UpdatePassword(userID, hashedPassword interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockIUserUtils)(nil).UpdatePassword), userID, hashedPassword)
}

// UpdateUser mocks base method.
func (m *MockIUserUtils) UpdateUser(userID uint, updates types.UserUpdateRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", userID, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockIUserUtilsMockRecorder) UpdateUser(userID, updates interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockIUserUtils)(nil).UpdateUser), userID, updates)
}

// ValidatePassword mocks base method.
func (m *MockIUserUtils) ValidatePassword(password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidatePassword", password)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidatePassword indicates an expected call of ValidatePassword.
func (mr *MockIUserUtilsMockRecorder) ValidatePassword(password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatePassword", reflect.TypeOf((*MockIUserUtils)(nil).ValidatePassword), password)
}
