services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - givegetgo-network
    depends_on:
      - givegetgo-user-backend
      - givegetgo-verification-backend
      - givegetgo-post-backend
      - givegetgo-bid-backend
      - givegetgo-match-backend

  givegetgo-user-backend:
    build:
      context: ./servers/user
    env_file:
      - ./servers/user/.env.user
    restart: unless-stopped
    networks:
      - givegetgo-network
    depends_on:
      - user-postgres
      - givegetgo-redis

  givegetgo-verification-backend:
    build:
      context: ./servers/verification
    env_file:
      - ./servers/verification/.env.verification
    restart: unless-stopped
    networks:
      - givegetgo-network
    depends_on:
      - verification-postgres
      - givegetgo-redis

  givegetgo-post-backend:
    build:
      context: ./servers/post
    env_file:
      - ./servers/post/.env.post
    restart: unless-stopped
    networks:
      - givegetgo-network
    depends_on:
      - post-postgres
      - givegetgo-redis

  givegetgo-bid-backend:
    build:
      context: ./servers/bid
    env_file:
      - ./servers/bid/.env.bid
    restart: unless-stopped
    networks:
      - givegetgo-network
    depends_on:
      - bid-postgres
      - givegetgo-redis
  
  givegetgo-match-backend:
    build:
      context: ./servers/match
    env_file:
      - ./servers/match/.env.match
    restart: unless-stopped
    networks:
      - givegetgo-network
    depends_on:
      - match-postgres
      - givegetgo-redis

  user-postgres:
    image: postgres
    container_name: givegetgo-eks-user-postgres-db
    networks:
      - givegetgo-network
    env_file:
      - ./servers/user/.env.user
    volumes:
      - user-postgres:/var/lib/postgresql/data

  verification-postgres:
    image: postgres
    container_name: givegetgo-eks-verification-postgres-db
    networks:
      - givegetgo-network
    env_file:
      - ./servers/verification/.env.verification
    volumes:
      - verification-postgres:/var/lib/postgresql/data

  post-postgres:
    image: postgres
    container_name: givegetgo-eks-post-postgres-db
    networks:
      - givegetgo-network
    env_file:
      - ./servers/post/.env.post
    volumes:
      - post-postgres:/var/lib/postgresql/data

  bid-postgres:
    image: postgres
    container_name: givegetgo-eks-bid-postgres-db
    networks:
      - givegetgo-network
    env_file:
      - ./servers/bid/.env.bid
    volumes:
      - bid-postgres:/var/lib/postgresql/data

  match-postgres:
    image: postgres
    container_name: givegetgo-eks-match-postgres-db
    networks:
      - givegetgo-network
    env_file:
      - ./servers/match/.env.match
    volumes:
      - match-postgres:/var/lib/postgresql/data

  givegetgo-redis:
    image: redis
    container_name: givegetgo-redis
    ports:
      - "6379:6379"
    networks:
      - givegetgo-network
    env_file:
      - ./redis/.env.redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf 
      - redis-data:/data

volumes:
  user-postgres:
  verification-postgres:
  post-postgres:
  bid-postgres:
  match-postgres:
  redis-data:

networks:
  givegetgo-network:
    driver: bridge
