version: '3.8'
services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - givegetgo-network
    depends_on:
      - user-service
      - verification-service
      - post-service
      - bid-service
      - match-service

  user-service:
    build:
      context: ./servers/user
    env_file:
      - ./servers/user/.env.user
    restart: unless-stopped
    networks:
      - givegetgo-network
    depends_on:
      - user-postgres
      - redis

  verification-service:
    build:
      context: ./servers/verification
    env_file:
      - ./servers/verification/.env.verification
    restart: unless-stopped
    networks:
      - givegetgo-network
    depends_on:
      - verification-postgres
      - redis

  post-service:
    build:
      context: ./servers/post
    env_file:
      - ./servers/post/.env.post
    restart: unless-stopped
    networks:
      - givegetgo-network
    depends_on:
      - post-postgres
      - redis

  bid-service:
    build:
      context: ./servers/bid
    env_file:
      - ./servers/bid/.env.bid
    restart: unless-stopped
    networks:
      - givegetgo-network
    depends_on:
      - bid-postgres
      - redis
  
  match-service:
    build:
      context: ./servers/match
    env_file:
      - ./servers/match/.env.match
    restart: unless-stopped
    networks:
      - givegetgo-network
    depends_on:
      - match-postgres
      - redis

  user-postgres:
    image: postgres
    container_name: user-postgres
    networks:
      - givegetgo-network
    env_file:
      - ./servers/user/.env.user
    volumes:
      - user-postgres:/var/lib/postgresql/data

  verification-postgres:
    image: postgres
    container_name: verification-postgres
    networks:
      - givegetgo-network
    env_file:
      - ./servers/verification/.env.verification
    volumes:
      - verification-postgres:/var/lib/postgresql/data

  post-postgres:
    image: postgres
    container_name: post-postgres
    networks:
      - givegetgo-network
    env_file:
      - ./servers/post/.env.post
    volumes:
      - post-postgres:/var/lib/postgresql/data

  bid-postgres:
    image: postgres
    container_name: bid-postgres
    networks:
      - givegetgo-network
    env_file:
      - ./servers/bid/.env.bid
    volumes:
      - bid-postgres:/var/lib/postgresql/data

  match-postgres:
    image: postgres
    container_name: match-postgres
    networks:
      - givegetgo-network
    env_file:
      - ./servers/match/.env.match
    volumes:
      - match-postgres:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - givegetgo-network
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf 
      - redis-data:/data
    command:
      redis-server /usr/local/etc/redis/redis.conf

volumes:
  user-postgres:
  verification-postgres:
  post-postgres:
  bid-postgres:
  match-postgres:
  redis-data:

networks:
  givegetgo-network:
    driver: bridge
