apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "match-postgres.fullname" . }}-pvc
  labels:
    {{- include "match-postgres.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
