# In templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "verification-postgres.secretName" . }}
type: Opaque
data:
  postgres-db: {{ .Values.postgres.db | b64enc | quote }}
  postgres-user: {{ .Values.postgres.user | b64enc | quote }}
  postgres-password: {{ .Values.postgres.password | b64enc | quote }}
