apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "user-postgres.fullname" . }}-pvc
  labels:
    {{- include "user-postgres.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
