apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis.fullname" . }}
data:
  redis.conf: |
    port 6379
    cluster-enabled yes
    cluster-config-file /data/nodes.conf
    cluster-node-timeout 5000
    appendonly yes
    protected-mode no
    # Customize these and other configurations as per your Redis setup
