apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-services-redis-egress
spec:
  podSelector:
    matchExpressions:
    - key: app.kubernetes.io/name
      operator: In
      values:
        - bid
        - match
        - post
        - user
        - verification
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
                app.kubernetes.io/name: redis
      ports:
        - protocol: TCP
          port: 6379
