apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-post-database-access
spec:
  podSelector:
    matchLabels:
        app.kubernetes.io/name: post
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
                app.kubernetes.io/name: post-postgres
      ports:
        - protocol: TCP
          port: 5432
