// Code generated by MockGen. DO NOT EDIT.
// Source: utils/user_utils.go
//
// Generated by this command:
//
//	mockgen -source=utils/user_utils.go -destination=utils/mock_user_utils.go -package=utils
//

// Package utils is a generated GoMock package.
package utils

import (
	reflect "reflect"
	schema "user_server/schema"

	gomock "go.uber.org/mock/gomock"
)

// MockIUserUtils is a mock of IUserUtils interface.
type MockIUserUtils struct {
	ctrl     *gomock.Controller
	recorder *MockIUserUtilsMockRecorder
}

// MockIUserUtilsMockRecorder is the mock recorder for MockIUserUtils.
type MockIUserUtilsMockRecorder struct {
	mock *MockIUserUtils
}

// NewMockIUserUtils creates a new mock instance.
func NewMockIUserUtils(ctrl *gomock.Controller) *MockIUserUtils {
	mock := &MockIUserUtils{ctrl: ctrl}
	mock.recorder = &MockIUserUtilsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUserUtils) EXPECT() *MockIUserUtilsMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockIUserUtils) CreateUser(username, email, hashedPassword string) (schema.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", username, email, hashedPassword)
	ret0, _ := ret[0].(schema.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockIUserUtilsMockRecorder) CreateUser(username, email, hashedPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockIUserUtils)(nil).CreateUser), username, email, hashedPassword)
}

// GetUserByEmail mocks base method.
func (m *MockIUserUtils) GetUserByEmail(email string) (schema.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", email)
	ret0, _ := ret[0].(schema.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockIUserUtilsMockRecorder) GetUserByEmail(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockIUserUtils)(nil).GetUserByEmail), email)
}

// HashPassword mocks base method.
func (m *MockIUserUtils) HashPassword(password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HashPassword", password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HashPassword indicates an expected call of HashPassword.
func (mr *MockIUserUtilsMockRecorder) HashPassword(password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HashPassword", reflect.TypeOf((*MockIUserUtils)(nil).HashPassword), password)
}

// RequestRegisterVerificationEmail mocks base method.
func (m *MockIUserUtils) RequestRegisterVerificationEmail(userID uint, username, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestRegisterVerificationEmail", userID, username, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequestRegisterVerificationEmail indicates an expected call of RequestRegisterVerificationEmail.
func (mr *MockIUserUtilsMockRecorder) RequestRegisterVerificationEmail(userID, username, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestRegisterVerificationEmail", reflect.TypeOf((*MockIUserUtils)(nil).RequestRegisterVerificationEmail), userID, username, email)
}

// SetUserEmailVerified mocks base method.
func (m *MockIUserUtils) SetUserEmailVerified(email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserEmailVerified", email)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUserEmailVerified indicates an expected call of SetUserEmailVerified.
func (mr *MockIUserUtilsMockRecorder) SetUserEmailVerified(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserEmailVerified", reflect.TypeOf((*MockIUserUtils)(nil).SetUserEmailVerified), email)
}

// ValidatePassword mocks base method.
func (m *MockIUserUtils) ValidatePassword(password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidatePassword", password)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidatePassword indicates an expected call of ValidatePassword.
func (mr *MockIUserUtilsMockRecorder) ValidatePassword(password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatePassword", reflect.TypeOf((*MockIUserUtils)(nil).ValidatePassword), password)
}
