apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: givegetgo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/GiveGetGo/givegetgo-backend.git
    path: kubernetes
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: givegetgo
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
