apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: givegetgo-redis
  namespace: argocd
spec:
  project: givegetgo-development
  source:
    repoURL: 'https://github.com/GiveGetGo/givegetgo-backend.git'
    path: 'charts/redis'
    targetRevision: development
  destination:
    server: "https://kubernetes.default.svc"
    namespace: givegetgo-development
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - dryRunMode=server
