// Code generated by MockGen. DO NOT EDIT.
// Source: utils/user_utils.go

// Package utils is a generated GoMock package.
package utils

import (
	reflect "reflect"
	schema "server/schema"

	gomock "github.com/golang/mock/gomock"
)

// MockIUserUtils is a mock of IUserUtils interface.
type MockIUserUtils struct {
	ctrl     *gomock.Controller
	recorder *MockIUserUtilsMockRecorder
}

// MockIUserUtilsMockRecorder is the mock recorder for MockIUserUtils.
type MockIUserUtilsMockRecorder struct {
	mock *MockIUserUtils
}

// NewMockIUserUtils creates a new mock instance.
func NewMockIUserUtils(ctrl *gomock.Controller) *MockIUserUtils {
	mock := &MockIUserUtils{ctrl: ctrl}
	mock.recorder = &MockIUserUtilsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUserUtils) EXPECT() *MockIUserUtilsMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockIUserUtils) CreateUser(username, email, hashedPassword string) (schema.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", username, email, hashedPassword)
	ret0, _ := ret[0].(schema.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockIUserUtilsMockRecorder) CreateUser(username, email, hashedPassword interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockIUserUtils)(nil).CreateUser), username, email, hashedPassword)
}

// GenerateRegisterVerificationCode mocks base method.
func (m *MockIUserUtils) GenerateRegisterVerificationCode(userID uint) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateRegisterVerificationCode", userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateRegisterVerificationCode indicates an expected call of GenerateRegisterVerificationCode.
func (mr *MockIUserUtilsMockRecorder) GenerateRegisterVerificationCode(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateRegisterVerificationCode", reflect.TypeOf((*MockIUserUtils)(nil).GenerateRegisterVerificationCode), userID)
}

// GetUserByEmail mocks base method.
func (m *MockIUserUtils) GetUserByEmail(email string) (schema.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", email)
	ret0, _ := ret[0].(schema.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockIUserUtilsMockRecorder) GetUserByEmail(email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockIUserUtils)(nil).GetUserByEmail), email)
}

// HashPassword mocks base method.
func (m *MockIUserUtils) HashPassword(password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HashPassword", password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HashPassword indicates an expected call of HashPassword.
func (mr *MockIUserUtilsMockRecorder) HashPassword(password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HashPassword", reflect.TypeOf((*MockIUserUtils)(nil).HashPassword), password)
}

// SendRegisterVerificationCode mocks base method.
func (m *MockIUserUtils) SendRegisterVerificationCode(user schema.User, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendRegisterVerificationCode", user, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendRegisterVerificationCode indicates an expected call of SendRegisterVerificationCode.
func (mr *MockIUserUtilsMockRecorder) SendRegisterVerificationCode(user, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendRegisterVerificationCode", reflect.TypeOf((*MockIUserUtils)(nil).SendRegisterVerificationCode), user, code)
}

// ValidatePassword mocks base method.
func (m *MockIUserUtils) ValidatePassword(password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidatePassword", password)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidatePassword indicates an expected call of ValidatePassword.
func (mr *MockIUserUtilsMockRecorder) ValidatePassword(password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatePassword", reflect.TypeOf((*MockIUserUtils)(nil).ValidatePassword), password)
}
